name: Update Notion Reading Tracker From Goodreads

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python -u script.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ vars.NOTION_DB_ID }}
          NOTION_DB_EVENT_ID: ${{ vars.NOTION_DB_EVENT_ID }}
          GOODREADS_ID: ${{ vars.GOODREADS_ID }}
